spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dev
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/tutor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: dev
    password: dev_password
    baseline-on-migrate: true
    validate-on-migrate: false 



